import numpy as np
import matplotlib.pyplot as plt
import random
import itertools
import networkx as nx
from collections import defaultdict
from matplotlib.cm import get_cmap
from matplotlib import cm  # for colormap
from tabulate import tabulate
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap, Normalize
import matplotlib as mpl
from MIRS import MIRS
from flpoAgent import flpoAgent
import os
import pickle
from pathlib import Path
import matplotlib as mpl
from matplotlib.ticker import MaxNLocator
from matplotlib.animation import FuncAnimation, PillowWriter
from mpl_toolkits.axes_grid1 import make_axes_locatable

# Use the same serif typeface across every plot generated by this module.
mpl.rcParams["font.family"] = "Times New Roman"
mpl.rcParams["font.serif"] = ["Times New Roman"]


def plotNetwork(
    figuresize,
    wp_xy,
    mask,
    dist_mat,
    sd_mat,
    routes,
    schedules,
    agent_colors,
    showEdgeLength=True,
    save_path=None,
    dpi=300,
    show_plot=True,
    show_segment_times=False,
    segment_time_decimals=1,
    segment_label_size=12,
    segment_label_offset=0.018,
):
    """
    Plot the waypoint network and directed agent traversals.

    For every directed edge traversal:

    - Agents are ordered by departure time.
    - The earliest-departing agent is shown farthest along the edge.
    - The latest-departing agent is shown closest to the source.
    - Each arrow is labeled with its departure and end time.
    - Labels are aligned with the corresponding arrow.
    - Labels remain upright while preserving the physical start/end order.

    Expected schedule convention
    ----------------------------
    For path edge path[k] -> path[k + 1]:

        schedule[k + 1] = departure time from path[k]
        schedule[k + 2] = arrival/end time at path[k + 1]
    """

    wp_xy = np.asarray(wp_xy)
    mask = np.asarray(mask)
    dist_mat = np.asarray(dist_mat)
    sd_mat = np.asarray(sd_mat)

    n_waypoints = wp_xy.shape[0]

    fig, ax = plt.subplots(figsize=figuresize)

    # Ensures that the data-coordinate direction of an edge is
    # represented correctly on screen.
    ax.set_aspect("equal", adjustable="box")

    # ============================================================
    # STEP 1: Plot waypoints
    # ============================================================
    waypoint_marker_size = 1100

    for waypoint_id, (x, y) in enumerate(wp_xy):
        ax.scatter(
            x,
            y,
            facecolor="white",
            edgecolor="black",
            linewidth=1.5,
            s=waypoint_marker_size,
            zorder=2,
        )

        ax.text(
            x,
            y,
            rf"{waypoint_id}",
            fontsize=28,
            color="black",
            fontweight="bold",
            ha="center",
            va="center",
            zorder=3,
        )

    # ============================================================
    # STEP 2: Plot network edges in the background
    # ============================================================
    for i in range(n_waypoints):
        for j in range(i + 1, n_waypoints):
            if mask[i, j] != 1:
                continue

            x1, y1 = wp_xy[i]
            x2, y2 = wp_xy[j]

            ax.plot(
                [x1, x2],
                [y1, y2],
                color="skyblue",
                alpha=0.2,
                linewidth=6,
                zorder=1,
            )

            if showEdgeLength:
                mid_x = (x1 + x2) / 2
                mid_y = (y1 + y2) / 2

                ax.text(
                    mid_x,
                    mid_y,
                    rf"${dist_mat[i, j]:.1f}$",
                    fontsize=8,
                    ha="center",
                    va="center",
                    zorder=4,
                    bbox={
                        "boxstyle": "round,pad=0.08",
                        "facecolor": "white",
                        "edgecolor": "none",
                        "alpha": 0.65,
                    },
                )

    # Resolve the waypoint marker radius in display coordinates so arrow tails
    # can begin at the visible edge of each waypoint disc.
    fig.canvas.draw()
    waypoint_radius_pixels = (
        np.sqrt(waypoint_marker_size) / 2.0
    ) * fig.dpi / 72.0

    # ============================================================
    # STEP 3: Collect directed edge traversals
    # ============================================================
    directed_edge_traversals = defaultdict(list)

    for agent_id, path in enumerate(routes):
        schedule = schedules[agent_id]

        # The final edge uses schedule[len(path)], so the schedule
        # must contain at least len(path) + 1 entries.
        minimum_schedule_length = len(path) + 1

        if len(schedule) < minimum_schedule_length:
            raise ValueError(
                f"Schedule for agent {agent_id} has length "
                f"{len(schedule)}, but route length {len(path)} "
                f"requires at least {minimum_schedule_length} entries."
            )

        for k in range(len(path) - 1):
            source = path[k]
            destination = path[k + 1]

            departure_time = schedule[k + 1]
            end_time = schedule[k + 2]

            directed_edge_traversals[(source, destination)].append(
                (agent_id, departure_time, end_time)
            )

    # ============================================================
    # STEP 4: Draw ordered directed arrows and time labels
    # ============================================================
    for (
        source,
        destination,
    ), traversals in directed_edge_traversals.items():

        source_x, source_y = wp_xy[source]
        destination_x, destination_y = wp_xy[destination]

        edge_dx = destination_x - source_x
        edge_dy = destination_y - source_y
        edge_length = np.hypot(edge_dx, edge_dy)

        if edge_length <= 1e-12:
            continue

        source_display = ax.transData.transform((source_x, source_y))
        direction_display = ax.transData.transform(
            (
                source_x + edge_dx / edge_length,
                source_y + edge_dy / edge_length,
            )
        ) - source_display
        display_direction_length = np.hypot(*direction_display)
        if display_direction_length <= 1e-12:
            continue

        source_edge_point = ax.transData.inverted().transform(
            source_display
            + waypoint_radius_pixels
            * direction_display
            / display_direction_length
        )
        source_offset_x = source_edge_point[0] - source_x
        source_offset_y = source_edge_point[1] - source_y

        # Every directed traversal uses the half-edge extending from
        # its source waypoint toward the midpoint of the full edge.
        half_dx = edge_dx / 2
        half_dy = edge_dy / 2

        # Unit vector perpendicular to the directed edge.
        #
        # When the edge direction reverses, this vector also reverses.
        # Therefore, labels for opposite travel directions naturally
        # appear on opposite sides of the edge.
        perpendicular_x = -edge_dy / edge_length
        perpendicular_y = edge_dx / edge_length

        # Earliest departure first.
        traversals = sorted(
            traversals,
            key=lambda traversal: traversal[1],
        )

        n_traversals = len(traversals)

        if n_traversals == 0:
            continue

        segment_dx = half_dx / n_traversals
        segment_dy = half_dy / n_traversals

        # Reduce label size when many agents traverse the same
        # directed edge.
        adaptive_label_size = max(
            4,
            segment_label_size
            - 0.35 * max(0, n_traversals - 3),
        )

        for rank, (
            agent_id,
            departure_time,
            end_time,
        ) in enumerate(traversals):

            # The earliest agent has rank 0 and should be visually
            # farthest from the source waypoint.
            position_index = n_traversals - 1 - rank

            segment_start_x = (
                source_x + position_index * segment_dx
                + source_offset_x
            )
            segment_start_y = (
                source_y + position_index * segment_dy
                + source_offset_y
            )

            # Leave a small visual gap between neighboring arrows.
            arrow_fraction = 0.92

            arrow_dx = arrow_fraction * segment_dx
            arrow_dy = arrow_fraction * segment_dy

            ax.quiver(
                segment_start_x,
                segment_start_y,
                arrow_dx,
                arrow_dy,
                angles="xy",
                scale_units="xy",
                scale=1,
                color=agent_colors[agent_id],
                width=0.004,
                headwidth=5,
                headlength=6,
                alpha=0.9,
                zorder=10 + position_index,
            )

            if not show_segment_times:
                continue

            # ----------------------------------------------------
            # Position the label at the center of the arrow
            # ----------------------------------------------------
            label_x = segment_start_x + 0.5 * arrow_dx
            label_y = segment_start_y + 0.5 * arrow_dy

            offset = segment_label_offset * edge_length

            label_x += offset * perpendicular_x
            label_y += offset * perpendicular_y

            # ----------------------------------------------------
            # Calculate the actual directed arrow angle
            # ----------------------------------------------------
            raw_angle = np.degrees(
                np.arctan2(arrow_dy, arrow_dx)
            )

            # Matplotlib text is easier to read when its rotation lies
            # between -90 and 90 degrees.
            #
            # If we rotate by 180 degrees to keep the text upright,
            # the readable text direction becomes opposite the actual
            # arrow direction. In that case, the time order and arrow
            # symbol must also be reversed.
            reverse_label = False

            if raw_angle > 90:
                text_angle = raw_angle - 180
                reverse_label = True

            elif raw_angle < -90:
                text_angle = raw_angle + 180
                reverse_label = True

            else:
                text_angle = raw_angle

            departure_string = (
                f"{departure_time:.{segment_time_decimals}f}"
            )
            end_string = (
                f"{end_time:.{segment_time_decimals}f}"
            )

            if reverse_label:
                # Reading direction is opposite the physical arrow:
                #
                # arrow head <- end time ... departure time <- tail
                time_label = (
                    end_string
                    + r"$\leftarrow$"
                    + departure_string
                )
            else:
                # Reading direction matches the physical arrow:
                #
                # tail -> departure time ... end time -> arrow head
                time_label = (
                    departure_string
                    + r"$\rightarrow$"
                    + end_string
                )

            ax.text(
                label_x,
                label_y,
                time_label,
                fontsize=adaptive_label_size,
                color="black",
                ha="center",
                va="center",
                rotation=text_angle,
                rotation_mode="anchor",

                # Critical: rotate text according to the transformed
                # data-coordinate direction of the arrow.
                transform_rotates_text=True,

                clip_on=True,
                zorder=30,
                bbox={
                    "boxstyle": "round,pad=0.10",
                    "facecolor": "white",
                    "edgecolor": "none",
                    "alpha": 0.75,
                },
            )

    # ============================================================
    # STEP 5: Agent-color strip
    # ============================================================
    if routes is not None and len(routes) > 0:
        n_agents = len(routes)

        strip_ax = fig.add_axes(
            [0.02, 0.1, 0.075, 0.8]
        )

        strip_ax.set_xlim(0, 1)
        strip_ax.set_ylim(0, n_agents)

        for agent_id in range(n_agents):
            agent_color = agent_colors[agent_id]

            strip_ax.add_patch(
                plt.Rectangle(
                    (0, agent_id),
                    1,
                    1,
                    color=agent_color,
                )
            )

            rgb = np.asarray(agent_color[:3])

            text_color = (
                "white"
                if np.mean(rgb) < 0.5
                else "black"
            )

            strip_ax.text(
                0.5,
                agent_id + 0.5,
                (
                    f"$a_{{{agent_id}}}$\n"
                    f"({int(sd_mat[agent_id, 0])}, "
                    f"{int(sd_mat[agent_id, 1])})"
                ),
                ha="center",
                va="center",
                fontsize=22,
                fontweight="bold",
                color=text_color,
            )

        strip_ax.axis("off")

        # Reserve space for the vertical color strip.
        fig.subplots_adjust(left=0.13)

    # ============================================================
    # Save/show/close
    # ============================================================
    # Allow the plot to use the requested figure dimensions.
    # transform_rotates_text=True keeps time labels aligned
    # with the visually transformed arrows.
    ax.set_aspect("auto")

    # Add a small amount of padding around the network.
    ax.margins(x=0.05, y=0.05)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.tick_params(axis="both", which="both", length=0)

    if save_path is not None:
        save_path = Path(save_path)
        save_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        fig.savefig(
            save_path,
            dpi=dpi,
            bbox_inches="tight",
        )

    if show_plot:
        plt.show()

    plt.close(fig)


def plot_edge_gradient_heatmap(
    figuresize,
    wp_xy,
    mask,
    grad_mat,
    save_path=None,
    dpi=300,
    show_plot=True,
    cmap_name="Greys",
    line_width=8,
):
    """
    Plot the waypoint network with each existing edge (i,j), i != j, colored on a
    white-to-black scale according to |d F_beta / d l_ij| (grad_mat), high gradient
    magnitude -> black, low magnitude -> white.
    """
    wp_xy = np.asarray(wp_xy)
    mask = np.asarray(mask)
    grad_mat = np.asarray(grad_mat)
    n_waypoints = wp_xy.shape[0]

    fig, ax = plt.subplots(figsize=figuresize)
    ax.set_aspect("equal", adjustable="box")

    edge_pairs = [
        (i, j)
        for i in range(n_waypoints)
        for j in range(i + 1, n_waypoints)
        if mask[i, j] == 1
    ]
    magnitudes = np.array([abs(grad_mat[i, j]) for i, j in edge_pairs]) if edge_pairs else np.array([0.0])
    vmax = magnitudes.max()
    norm = Normalize(vmin=0.0, vmax=vmax if vmax > 0 else 1.0)
    cmap = plt.get_cmap(cmap_name)

    for i, j in edge_pairs:
        x1, y1 = wp_xy[i]
        x2, y2 = wp_xy[j]
        ax.plot(
            [x1, x2],
            [y1, y2],
            color=cmap(norm(abs(grad_mat[i, j]))),
            linewidth=line_width,
            solid_capstyle="round",
            zorder=1,
        )

    waypoint_marker_size = 1100
    for waypoint_id, (x, y) in enumerate(wp_xy):
        ax.scatter(
            x, y,
            facecolor="white",
            edgecolor="black",
            linewidth=1.5,
            s=waypoint_marker_size,
            zorder=2,
        )
        ax.text(
            x, y,
            rf"{waypoint_id}",
            fontsize=28,
            color="black",
            fontweight="bold",
            ha="center",
            va="center",
            zorder=3,
        )

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, shrink=0.8)
    cbar.set_label(r"$|\partial F_\beta / \partial l_{ij}|$", fontsize=18)

    ax.set_title(r"Edge gradient heat-map at $\beta=\beta_{max}$", fontsize=20)
    ax.set_xticks([])
    ax.set_yticks([])

    if save_path is not None:
        save_path = Path(save_path)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_path, dpi=dpi, bbox_inches="tight")

    if show_plot:
        plt.show()

    plt.close(fig)


def animate_agent_routes(
    wp_xy,
    mask,
    routes,
    schedules,
    agent_colors,
    save_path,
    figuresize=(12, 9),
    fps=10,
    max_frames=240,
    dpi=150,
):
    """Animate agents moving along their scheduled routes and save a GIF."""
    wp_xy = np.asarray(wp_xy, dtype=float)
    mask = np.asarray(mask)
    n_agents = len(routes)

    if n_agents == 0:
        raise ValueError("Cannot animate a scenario with no agent routes.")

    route_data = []
    final_times = []
    for agent_id, route in enumerate(routes):
        route = [int(waypoint_id) for waypoint_id in route]
        if not route:
            continue

        values = np.asarray(schedules[agent_id], dtype=float).reshape(-1)
        if values.size >= len(route) + 1:
            arrival_times = values[1 : len(route) + 1]
        elif values.size >= len(route):
            arrival_times = values[: len(route)]
        else:
            raise ValueError(
                f"Schedule for agent {agent_id} has {values.size} entries, "
                f"but route requires {len(route)} arrival times."
            )

        if not np.all(np.isfinite(arrival_times)):
            raise ValueError(f"Schedule for agent {agent_id} contains non-finite times.")
        if np.any(np.diff(arrival_times) < 0):
            raise ValueError(f"Schedule for agent {agent_id} is not chronological.")

        route_data.append((agent_id, route, arrival_times))
        final_times.append(float(arrival_times[-1]))

    if not route_data:
        raise ValueError("Cannot animate a scenario with no valid routes.")

    start_time = min(
        float(arrival_times[0])
        for _, _, arrival_times in route_data
    )
    end_time = max(final_times)
    if end_time <= start_time:
        end_time = start_time + 1.0

    requested_frames = int(np.ceil((end_time - start_time) * fps)) + 1
    frame_count = max(2, min(requested_frames, max(2, int(max_frames))))
    frame_times = np.linspace(start_time, end_time, frame_count)

    fig, ax = plt.subplots(figsize=figuresize)
    ax.set_aspect("equal", adjustable="box")

    for i in range(len(wp_xy)):
        for j in range(i + 1, len(wp_xy)):
            if mask[i, j] == 1:
                ax.plot(
                    [wp_xy[i, 0], wp_xy[j, 0]],
                    [wp_xy[i, 1], wp_xy[j, 1]],
                    color="skyblue",
                    alpha=0.3,
                    linewidth=3,
                    zorder=1,
                )

    ax.scatter(
        wp_xy[:, 0],
        wp_xy[:, 1],
        s=700,
        facecolor="white",
        edgecolor="black",
        linewidth=1.5,
        zorder=2,
    )
    for waypoint_id, (x, y) in enumerate(wp_xy):
        ax.text(
            x,
            y,
            str(waypoint_id),
            fontsize=22,
            color="black",
            fontweight="bold",
            ha="center",
            va="center",
            zorder=3,
        )

    agents = ax.scatter(
        [],
        [],
        s=260,
        edgecolors="black",
        linewidths=1.0,
        zorder=5,
    )
    time_text = ax.text(
        0.02,
        0.98,
        "",
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=22,
        fontweight="bold",
        bbox={"facecolor": "white", "alpha": 0.8, "edgecolor": "none"},
        zorder=10,
    )

    all_positions = wp_xy[np.concatenate([np.asarray(route) for _, route, _ in route_data])]
    x_min, y_min = np.min(all_positions, axis=0)
    x_max, y_max = np.max(all_positions, axis=0)
    x_pad = max((x_max - x_min) * 0.08, 1.0)
    y_pad = max((y_max - y_min) * 0.08, 1.0)
    ax.set_xlim(x_min - x_pad, x_max + x_pad)
    ax.set_ylim(y_min - y_pad, y_max + y_pad)
    ax.set_xticks([])
    ax.set_yticks([])

    def position_at_time(route, arrival_times, current_time):
        if current_time <= arrival_times[0]:
            return wp_xy[route[0]]
        for index in range(1, len(route)):
            segment_start = arrival_times[index - 1]
            segment_end = arrival_times[index]
            if current_time <= segment_end:
                duration = segment_end - segment_start
                if duration <= 0:
                    return wp_xy[route[index]]
                fraction = (current_time - segment_start) / duration
                return (
                    wp_xy[route[index - 1]]
                    + fraction
                    * (wp_xy[route[index]] - wp_xy[route[index - 1]])
                )
        return wp_xy[route[-1]]

    def update(frame_index):
        current_time = frame_times[frame_index]
        positions = np.asarray(
            [
                position_at_time(route, arrival_times, current_time)
                for _, route, arrival_times in route_data
            ]
        )
        agents.set_offsets(positions)
        agents.set_facecolors(
            [agent_colors[agent_id] for agent_id, _, _ in route_data]
        )
        time_text.set_text(f"Time: {current_time:.2f} s")
        return agents, time_text

    animation = FuncAnimation(
        fig,
        update,
        frames=frame_count,
        interval=1000 / max(fps, 1),
        blit=True,
    )
    save_path = Path(save_path)
    save_path.parent.mkdir(parents=True, exist_ok=True)
    animation.save(save_path, writer=PillowWriter(fps=fps), dpi=dpi)
    plt.close(fig)


def plot_agent_waypoint_schedules(
    routes,
    schedules,
    schedule_matrix,
    association_matrix,
    process_T,
    tolArray,
    agent_colors,
    figuresize,
    marker_size=200,
    index_size=480,
    x_tick_size=50,
    y_tick_size=50,
    x_label_size=48,
    y_label_size=48,
    save_path=None,
    dpi=300,
    show_plot=True,
):
    """
    Plot the schedule from the agent perspective.

    Each row corresponds to one agent and the markers show the waypoint IDs it
    visits in chronological order. This is the complementary view to the
    waypoint-centric timeline plot, which groups by waypoint instead of agent.
    """
    schedule_matrix = np.asarray(schedule_matrix)
    association_matrix = np.asarray(association_matrix)

    if association_matrix.ndim != 2:
        raise ValueError("association_matrix must be a two-dimensional array.")

    if schedule_matrix.shape != association_matrix.shape:
        raise ValueError(
            "schedule_matrix and association_matrix must have the same shape. "
            f"Received {schedule_matrix.shape} and {association_matrix.shape}."
        )

    n_agents, n_waypoints = association_matrix.shape
    band_font_size = max(22, x_tick_size, y_tick_size)

    fig, ax = plt.subplots(figsize=figuresize)
    waypoint_cmap = plt.get_cmap("tab20", max(n_waypoints, 1))
    leftmost_label_x = None
    largest_label_offset = 0.0

    # Make the travel bands substantial enough to carry the enlarged waypoint labels.
    # Keep the thickness bounded so neighboring agent rows remain visually distinct.
    band_half_height = max(0.3, min(0.48, 1.3 / max(n_agents, 1) / 2.0))

    for agent_id in range(n_agents):
        if agent_id >= len(routes):
            continue

        route = list(routes[agent_id])
        if not route:
            continue

        valid_pairs = []
        for waypoint_id in route:
            waypoint_id = int(waypoint_id)
            if waypoint_id < 0 or waypoint_id >= schedule_matrix.shape[1]:
                continue
            arrival_time = schedule_matrix[agent_id, waypoint_id]
            if np.isfinite(arrival_time):
                valid_pairs.append((float(arrival_time), waypoint_id))

        if len(valid_pairs) < 2:
            continue

        valid_times = np.asarray([time for time, _ in valid_pairs], dtype=float)
        time_span = float(np.ptp(valid_times)) if valid_times.size > 1 else 1.0
        label_offset = max(0.25, 0.012 * time_span)
        largest_label_offset = max(largest_label_offset, label_offset)

        agent_color = agent_colors.get(agent_id, "black")
        band_color = mpl.colors.to_rgba(agent_color, alpha=0.42)

        for i in range(len(valid_pairs) - 1):
            start_time, start_wp = valid_pairs[i]
            end_time, end_wp = valid_pairs[i + 1]
            segment_start = max(start_time, 0.0)
            segment_end = float(end_time)
            segment_width = max(segment_end - segment_start, 0.0)
            if segment_width <= 0:
                continue

            y0 = agent_id - band_half_height
            y1 = agent_id + band_half_height

            # Use the full segment interval; no artificial separator to create a seam.
            band_left = segment_start
            band_right = segment_end

            ax.fill_betweenx(
                [y0, y1],
                band_left,
                band_right,
                color=band_color,
                alpha=0.9,
                linewidth=1.0,
                zorder=2,
            )

        for arrival_time, waypoint_id in valid_pairs:
            waypoint_color = waypoint_cmap(waypoint_id % max(1, n_waypoints))
            ax.plot(
                arrival_time,
                agent_id,
                marker="|",
                linestyle="none",
                markersize=max(7, min(marker_size, 18)),
                markerfacecolor="white",
                markeredgecolor="white",
                markeredgewidth=4.0,
                zorder=5,
            )
            ax.text(
                arrival_time - label_offset,
                agent_id,
                str(waypoint_id),
                fontsize=band_font_size,
                ha="right",
                va="center",
                color="black",
                zorder=6,
            )
            label_x = arrival_time - label_offset
            leftmost_label_x = (
                label_x
                if leftmost_label_x is None
                else min(leftmost_label_x, label_x)
            )

    if leftmost_label_x is not None:
        current_x_min, current_x_max = ax.get_xlim()
        x_span = max(current_x_max - current_x_min, 1.0)
        left_padding = max(largest_label_offset, 0.08 * x_span)
        ax.set_xlim(min(current_x_min, leftmost_label_x - left_padding), current_x_max)

    ax.set_ylim(-0.5, n_agents - 0.5)
    ax.set_yticks(np.arange(n_agents))
    ax.set_yticklabels([str(i) for i in range(n_agents)], fontsize=max(22, y_tick_size))
    ax.tick_params(axis="x", labelsize=max(22, x_tick_size))
    ax.set_xlabel("Time (s)", fontsize=max(22, x_label_size))
    ax.set_ylabel("Agent ID", fontsize=max(22, y_label_size))
    ax.grid(axis="x", linestyle="--", alpha=0.7)
    ax.grid(axis="y", linestyle="--", alpha=0.3)
    ax.margins(x=0.03)

    if save_path is not None:
        fig.savefig(save_path, dpi=dpi, bbox_inches="tight")

    if show_plot:
        plt.show()

    plt.close(fig)


def plot_waypoint_agent_schedules(
    routes,
    schedules,
    schedule_matrix,
    association_matrix,
    process_T,
    tolArray,
    agent_colors,
    figuresize,

    # Timeline appearance
    bar_thickness=0.12,
    marker_size=200,
    index_size=480,

    # Axis text
    x_tick_size=70,
    y_tick_size=70,
    x_label_size=48,
    y_label_size=48 ,

    # Colorbar text
    colorbar_tick_size=14,
    colorbar_label_size=16,

    # Safety-color interpretation
    safe_gap_multiplier=2.0,

    # Output
    save_path=None,
    dpi=300,
    show_plot=True,
):
    """
    Plot waypoint arrival timelines and inter-agent safety gaps.

    Safety-color interpretation
    ---------------------------
    gap < tolerance
        Red-to-yellow region: unsafe.

    gap = tolerance
        Yellow: boundary of the safety constraint.

    tolerance < gap < safe_gap_multiplier * tolerance
        Yellow-to-green region.

    gap >= safe_gap_multiplier * tolerance
        Green: comfortably safe.

    Tick behavior
    -------------
    Grid lines are shown at every generated x-axis tick and every active
    waypoint row. Tick labels are displayed only when sufficient space is
    available, based on the figure size and requested font sizes.

    Notes
    -----
    The following arguments are retained for compatibility but are not used
    by this single-panel version:

        routes, schedules, process_T
    """

    schedule_matrix = np.asarray(schedule_matrix)
    association_matrix = np.asarray(association_matrix)
    tolArray = np.asarray(tolArray)

    if association_matrix.ndim != 2:
        raise ValueError("association_matrix must be a two-dimensional array.")

    if schedule_matrix.shape != association_matrix.shape:
        raise ValueError(
            "schedule_matrix and association_matrix must have the same shape. "
            f"Received {schedule_matrix.shape} and "
            f"{association_matrix.shape}."
        )

    n_agents, n_waypoints = association_matrix.shape

    if len(tolArray) < n_waypoints:
        raise ValueError(
            f"tolArray has length {len(tolArray)}, but the problem has "
            f"{n_waypoints} waypoints."
        )

    # ============================================================
    # Collect active waypoint information before plotting
    # ============================================================
    active_waypoint_data = []

    for waypoint_idx in range(n_waypoints):
        # Use a threshold instead of exact floating-point equality.
        agent_indices = np.flatnonzero(
            association_matrix[:, waypoint_idx] > 0.5
        )

        if len(agent_indices) == 0:
            continue

        arrival_times = schedule_matrix[
            agent_indices,
            waypoint_idx,
        ]

        # Sort agents by arrival time.
        order = np.argsort(arrival_times)

        sorted_agents = agent_indices[order]
        sorted_times = arrival_times[order]

        active_waypoint_data.append(
            {
                "waypoint": waypoint_idx,
                "agents": sorted_agents,
                "times": sorted_times,
                "tolerance": float(tolArray[waypoint_idx]),
            }
        )

    n_active_waypoints = len(active_waypoint_data)

    if n_active_waypoints == 0:
        raise ValueError(
            "No active waypoints were found in association_matrix."
        )

    # ============================================================
    # Create figure
    # ============================================================
    fig, ax = plt.subplots(figsize=figuresize)

    # Explicit red -> yellow -> green map.
    safety_cmap = LinearSegmentedColormap.from_list(
        "safety_cmap",
        [
            (0.0, "red"),
            (0.5, "gold"),
            (1.0, "green"),
        ],
    )

    safety_norm = mpl.colors.Normalize(vmin=0.0, vmax=1.0)

    # ============================================================
    # Adapt marker and marker-label sizes to the available height
    # ============================================================
    figure_height_points = float(figuresize[1]) * 72.0

    available_points_per_row = (
        figure_height_points / max(n_active_waypoints, 1)
    )

    effective_marker_size = max(
        10.0,
        min(marker_size * 4.0, 0.75 * available_points_per_row),
    )

    effective_agent_font_size = max(
        12.0,
        min(index_size * 0.8, 0.35 * available_points_per_row),
    )

    # ============================================================
    # Draw waypoint rows
    # ============================================================
    for row_idx, waypoint_data in enumerate(active_waypoint_data):
        waypoint_idx = waypoint_data["waypoint"]
        sorted_agents = waypoint_data["agents"]
        sorted_times = waypoint_data["times"]
        tolerance = waypoint_data["tolerance"]

        # --------------------------------------------------------
        # Draw safety-colored gaps
        # --------------------------------------------------------
        for i in range(len(sorted_times) - 1):
            time_1 = float(sorted_times[i])
            time_2 = float(sorted_times[i + 1])

            gap = time_2 - time_1

            if tolerance > 0:
                # gap = tolerance maps exactly to 0.5: yellow.
                safety_score = gap / (
                    safe_gap_multiplier * tolerance
                )
            else:
                safety_score = 1.0 if gap > 0 else 0.0

            safety_score = float(
                np.clip(safety_score, 0.0, 1.0)
            )

            segment_color = safety_cmap(safety_score)

            ax.fill_betweenx(
                [
                    row_idx - bar_thickness,
                    row_idx + bar_thickness,
                ],
                time_1,
                time_2,
                color=segment_color,
                alpha=0.50,
                zorder=2,
            )

        # --------------------------------------------------------
        # Draw agent markers and labels
        # --------------------------------------------------------
        for arrival_time, agent_id in zip(
            sorted_times,
            sorted_agents,
        ):
            agent_id = int(agent_id)
            agent_color = agent_colors[agent_id]

            ax.plot(
                arrival_time,
                row_idx,
                marker="s",
                linestyle="none",
                markersize=effective_marker_size,
                markerfacecolor=agent_color,
                markeredgecolor="white",
                markeredgewidth=1.5,
                zorder=5,
            )

            # Select contrasting text color.
            color_obj = mpl.colors.to_rgba(agent_color)
            rgb = np.asarray(color_obj[:3], dtype=float)

            luminance = (
                0.2126 * rgb[0]
                + 0.7152 * rgb[1]
                + 0.0722 * rgb[2]
            )

            marker_text_color = (
                "black" if luminance > 0.55 else "white"
            )

            # Use only the numeric index inside the marker.
            # This is more compact than a_i for large scenarios.
            # ax.text(
            #     arrival_time,
            #     row_idx,
            #     str(agent_id),
            #     fontsize=effective_agent_font_size,
            #     color=marker_text_color,
            #     ha="center",
            #     va="center",
            #     fontweight="bold",
            #     zorder=6,
            #     clip_on=True,
            # )

    # ============================================================
    # Basic axis formatting
    # ============================================================
    ax.set_ylim(
        -0.5,
        n_active_waypoints - 0.5,
    )
    ax.tick_params(axis="both", which="major", labelsize=max(12, x_tick_size))
    ax.tick_params(axis="y", which="major", labelsize=max(12, y_tick_size))

    ax.set_xlabel(
        "Time (s)",
        fontsize=max(18, x_label_size),
    )

    ax.set_ylabel(
        r"$w_i$",
        fontsize=max(18, y_label_size),
    )

    ax.margins(x=0.03)

    # ============================================================
    # Colorbar in a separate axis
    # ============================================================
    scalar_mappable = mpl.cm.ScalarMappable(
        cmap=safety_cmap,
        norm=safety_norm,
    )
    scalar_mappable.set_array([])

    # This creates dedicated space to the right rather than placing
    # the colorbar inside the timeline axes.
    divider = make_axes_locatable(ax)

    colorbar_ax = divider.append_axes(
        "right",
        size="3.5%",
        pad=0.45,
    )

    colorbar = fig.colorbar(
        scalar_mappable,
        cax=colorbar_ax,
        orientation="vertical",
    )

    colorbar.set_ticks(
        [0.0, 0.5, 1.0]
    )

    colorbar.set_ticklabels(
        [
            "Unsafe",
            "Boundary",
            "Safe",
        ]
    )

    colorbar.ax.tick_params(
        labelsize=colorbar_tick_size,
    )

    colorbar.set_label(
        (
            "Inter-agent gap safety\n"
            rf"(yellow: gap = tolerance; "
            rf"green: gap $\geq$ "
            rf"{safe_gap_multiplier:g}$\times$tolerance)"
        ),
        fontsize=colorbar_label_size,
        labelpad=12,
    )

    for spine in colorbar.ax.spines.values():
        spine.set_visible(True)
        spine.set_alpha(0.4)

    # Draw once so that the final axis dimensions are available.
    fig.canvas.draw()

    # ============================================================
    # Adaptive x-axis ticks
    # ============================================================
    axis_bbox_inches = (
        ax.get_window_extent()
        .transformed(fig.dpi_scale_trans.inverted())
    )

    axis_width_inches = axis_bbox_inches.width
    axis_height_inches = axis_bbox_inches.height

    x_min, x_max = ax.get_xlim()

    if np.isclose(x_min, x_max):
        x_min -= 1.0
        x_max += 1.0
        ax.set_xlim(x_min, x_max)

    # Number of x-grid lines depends on physical axis width.
    x_grid_bins = int(
        np.clip(
            axis_width_inches * 1.4,
            5,
            40,
        )
    )

    x_locator = MaxNLocator(
        nbins=x_grid_bins,
        min_n_ticks=4,
    )

    x_grid_ticks = np.asarray(
        x_locator.tick_values(x_min, x_max)
    )

    # Remove locator ticks lying outside the displayed range.
    x_grid_ticks = x_grid_ticks[
        (x_grid_ticks >= x_min)
        & (x_grid_ticks <= x_max)
    ]

    if len(x_grid_ticks) < 2:
        x_grid_ticks = np.linspace(
            x_min,
            x_max,
            5,
        )

    # Estimate the number of labels that fit without overlap.
    axis_width_points = axis_width_inches * 72.0

    max_visible_x_labels = max(
        2,
        int(
            axis_width_points
            / max(4.5 * x_tick_size, 1)
        ),
    )

    x_label_step = max(
        1,
        int(
            np.ceil(
                len(x_grid_ticks)
                / max_visible_x_labels
            )
        ),
    )

    x_span = abs(x_max - x_min)

    def format_x_value(value):
        if x_span >= 100:
            return f"{value:,.0f}"

        if x_span >= 10:
            return f"{value:.1f}".rstrip("0").rstrip(".")

        return f"{value:.2f}".rstrip("0").rstrip(".")

    x_tick_labels = []

    for tick_index, tick_value in enumerate(x_grid_ticks):
        show_label = (
            tick_index % x_label_step == 0
            or tick_index == len(x_grid_ticks) - 1
        )

        if show_label:
            x_tick_labels.append(
                format_x_value(tick_value)
            )
        else:
            x_tick_labels.append("")

    ax.set_xticks(x_grid_ticks)

    ax.set_xticklabels(
        x_tick_labels,
        fontsize=x_tick_size,
    )

    # ============================================================
    # Adaptive y-axis labels
    # ============================================================
    # All active waypoint rows receive ticks and grid lines.
    y_grid_ticks = np.arange(n_active_waypoints)

    axis_height_points = axis_height_inches * 72.0

    max_visible_y_labels = max(
        2,
        int(
            axis_height_points
            / max(1.8 * y_tick_size, 1)
        ),
    )

    y_label_step = max(
        1,
        int(
            np.ceil(
                n_active_waypoints
                / max_visible_y_labels
            )
        ),
    )

    y_tick_labels = []

    for row_idx, waypoint_data in enumerate(active_waypoint_data):
        waypoint_idx = waypoint_data["waypoint"]

        show_label = (
            row_idx % y_label_step == 0
            or row_idx == n_active_waypoints - 1
        )

        if show_label:
            y_tick_labels.append(
                rf"${waypoint_idx}$"
            )
        else:
            y_tick_labels.append("")

    ax.set_yticks(y_grid_ticks)

    ax.set_yticklabels(
        y_tick_labels,
        fontsize=y_tick_size,
    )

    # ============================================================
    # Grid lines
    # ============================================================
    # Every generated x tick has a vertical grid line, even when
    # its numeric label is hidden.
    ax.grid(
        axis="x",
        which="major",
        linestyle="--",
        linewidth=0.8,
        alpha=0.55,
        zorder=0,
    )

    # Every active waypoint row has a horizontal grid line, even
    # when its waypoint number is hidden.
    ax.grid(
        axis="y",
        which="major",
        linestyle="--",
        linewidth=0.8,
        alpha=0.35,
        zorder=0,
    )

    ax.set_axisbelow(True)

    # ============================================================
    # Save/show/close
    # ============================================================
    if save_path is not None:
        save_path = Path(save_path)

        save_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        fig.savefig(
            save_path,
            dpi=dpi,
            bbox_inches="tight",
        )

    if show_plot:
        plt.show()

    plt.close(fig)


def plot_agent_waypoint_associations_vs_beta(
    b_arr,
    chi_arr,
    num_betas=6,
    subplot_size=None,
    ncols=None,
    marker_size=None,
    x_tick_size=22,
    y_tick_size=22,
    save_path=None,
    dpi=300,
    show_plot=True,
):
    """
    Plot the soft agent-waypoint association matrix (CBF method) at selected beta steps.

    Subplots are produced for up to ``num_betas`` values (default 6), evenly spaced
    across the annealing trajectory and guaranteed to include the initial and final
    beta values. Each subplot is a grid with agents on the y-axis and waypoints on the
    x-axis; a filled disc marks each (agent, waypoint) pair, greyscale-shaded by the
    soft reach probability in ``chi_arr`` (black = 1, white = 0).
    """
    b_arr = np.asarray(b_arr)
    chi_arr = np.asarray(chi_arr)

    if chi_arr.ndim != 3:
        raise ValueError(
            "chi_arr must have shape (n_beta, n_agents, n_waypoints), "
            f"got array with ndim={chi_arr.ndim}."
        )

    n_beta_total, n_agents, n_waypoints = chi_arr.shape
    if b_arr.shape[0] != n_beta_total:
        raise ValueError(
            f"b_arr length ({b_arr.shape[0]}) does not match the number of "
            f"beta steps in chi_arr ({n_beta_total})."
        )

    if num_betas is not None and n_beta_total > num_betas:
        selected_indices = np.round(np.linspace(0, n_beta_total - 1, num_betas)).astype(int)
        selected_indices[0] = 0
        selected_indices[-1] = n_beta_total - 1
        b_arr = b_arr[selected_indices]
        chi_arr = chi_arr[selected_indices]

    n_beta = len(b_arr)
    soft_assoc_arr = np.clip(chi_arr, 0.0, 1.0)

    ncols = ncols or min(3, n_beta)
    nrows = int(np.ceil(n_beta / ncols))

    aspect_ratio = n_waypoints / max(1, n_agents)
    if subplot_size is None:
        sub_w = 6.0
        plot_h = max(1.8, min(4.5, sub_w / aspect_ratio))
        sub_h = plot_h + 0.75
    else:
        sub_w = float(subplot_size)
        sub_h = float(subplot_size)
        plot_h = sub_h

    fig, axes = plt.subplots(
        nrows,
        ncols,
        figsize=(sub_w * ncols + 0.8, sub_h * nrows + 0.5),
        squeeze=False,
        constrained_layout=True,
    )

    agent_grid, waypoint_grid = np.meshgrid(
        np.arange(n_agents), np.arange(n_waypoints), indexing="ij"
    )

    if marker_size is None:
        pts_per_cell_x = (sub_w * 0.85 / n_waypoints) * 72
        pts_per_cell_y = (plot_h * 0.85 / n_agents) * 72
        pts_per_cell = min(pts_per_cell_x, pts_per_cell_y)
        effective_marker_size = max(45, min(450, 0.55 * (pts_per_cell ** 2)))
    else:
        effective_marker_size = marker_size

    scatter = None
    for beta_idx in range(nrows * ncols):
        row, col = divmod(beta_idx, ncols)
        ax = axes[row][col]

        if beta_idx >= n_beta:
            ax.axis("off")
            continue

        soft_mat = soft_assoc_arr[beta_idx]

        scatter = ax.scatter(
            waypoint_grid.flatten(),
            agent_grid.flatten(),
            s=effective_marker_size,
            c=soft_mat.flatten(),
            cmap="gray_r",
            vmin=0.0,
            vmax=1.0,
            edgecolors="black",
            linewidths=0.6,
            zorder=3,
        )

        ax.set_xlim(-0.5, n_waypoints - 0.5)
        ax.set_ylim(-0.5, n_agents - 0.5)
        ax.invert_yaxis()
        ax.set_aspect("equal")

        if n_waypoints <= 16:
            ax.set_xticks(np.arange(n_waypoints))
        elif n_waypoints <= 30:
            ax.set_xticks(np.arange(0, n_waypoints, 2))
        else:
            ax.set_xticks(np.arange(0, n_waypoints, 5))

        if n_agents <= 16:
            ax.set_yticks(np.arange(n_agents))
        elif n_agents <= 30:
            ax.set_yticks(np.arange(0, n_agents, 2))
        else:
            ax.set_yticks(np.arange(0, n_agents, 5))

        ax.tick_params(axis="x", which="major", labelsize=x_tick_size)
        ax.tick_params(axis="y", which="major", labelsize=y_tick_size)
        ax.set_title(rf"$\beta$ = {b_arr[beta_idx]:.3g}", fontsize=22, fontweight="bold")
        ax.grid(True, linestyle=":", alpha=0.35, zorder=0)

        if col == 0:
            ax.set_ylabel("Agent ID", fontsize=22, fontweight="bold")
        if row == nrows - 1 or beta_idx + ncols >= n_beta:
            ax.set_xlabel("Waypoint ID", fontsize=22, fontweight="bold")

    # fig.suptitle("Soft Agent-Waypoint Associations vs. Beta (CBF)", fontsize=22, fontweight="bold")

    if scatter is not None:
        cbar = fig.colorbar(scatter, ax=axes, shrink=0.85, pad=0.02, aspect=25)
        cbar.set_label("Soft association (reach probability)", fontsize=22, fontweight="bold")
        cbar.ax.tick_params(labelsize=22)
        
    if save_path is not None:
        save_path = Path(save_path)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_path, dpi=dpi, bbox_inches="tight")

    if show_plot:
        plt.show()

    plt.close(fig)


def plot_path_probabilities_vs_beta(
    solution_data=None,
    b_arr=None,
    T_array=None,
    V_array=None,
    mask=None,
    dist_mat=None,
    sd_mat=None,
    start_times=None,
    speed_lim_mat=None,
    processing_time=None,
    inf=1e5,
    offset_energy=1,
    self_hop=0,
    stagewise_cost_coeffs=None,
    agent_routes=None,
    num_agents=3,
    num_paths=5,
    agent_indices=None,
    seed=None,
    x_tick_size=22,
    y_tick_size=22,
    label_size=22,
    title_size=22,
    legend_size=22,
    save_dir=None,
    save_path=None,
    dpi=300,
    show_plot=True,
):
    """
    Plot the evolution of path probabilities as a function of beta for sampled agents.

    Generates one plot per agent, where each plot is a matrix heatmap showing the path
    probabilities of ``num_paths`` sampled paths across the beta annealing schedule.
    Plots are saved individually into the specified directory.
    """
    if solution_data is not None:
        b_arr = solution_data.get("b_arr", b_arr)
        T_array = solution_data.get("T_array", T_array)
        V_array = solution_data.get("V_array", V_array)
        mask = solution_data.get("mask", mask)
        dist_mat = solution_data.get("dist_mat", dist_mat)
        sd_mat = solution_data.get("sd_mat", sd_mat)
        start_times = solution_data.get("start_times", start_times)
        speed_lim_mat = solution_data.get("speed_lim_mat", speed_lim_mat)
        processing_time = solution_data.get("processing_time", processing_time)
        inf = solution_data.get("inf", inf)
        offset_energy = solution_data.get("offset_energy", offset_energy)
        self_hop = solution_data.get("self_hop", self_hop)
        stagewise_cost_coeffs = solution_data.get("stagewise_cost_coeffs", stagewise_cost_coeffs)
        agent_routes = solution_data.get("agent_routes", agent_routes)
        if seed is None:
            seed = solution_data.get("seed", 42)

    if b_arr is None or T_array is None or V_array is None or mask is None or dist_mat is None or sd_mat is None:
        raise ValueError("Missing required solution data arrays for path probability computation.")

    b_arr = np.asarray(b_arr)
    T_array = np.asarray(T_array)
    V_array = np.asarray(V_array)
    mask = np.asarray(mask)
    dist_mat = np.asarray(dist_mat)
    sd_mat = np.asarray(sd_mat)

    if stagewise_cost_coeffs is None:
        stagewise_cost_coeffs = np.array([0.1, 10.0, 0.1], dtype=float)

    n_beta = len(b_arr)
    n_agents_total = sd_mat.shape[0]
    n_wp = mask.shape[0]

    if agent_indices is not None:
        selected_agents = [int(i) for i in agent_indices if 0 <= int(i) < n_agents_total]
    else:
        rng = np.random.RandomState(seed if seed is not None else 42)
        n_sel = min(num_agents, n_agents_total)
        selected_agents = list(rng.choice(n_agents_total, size=n_sel, replace=False))
        selected_agents.sort()

    if len(selected_agents) == 0:
        raise ValueError("No valid agents selected for path probability plotting.")

    target_dir = None
    if save_dir is not None:
        target_dir = Path(save_dir)
    elif save_path is not None:
        target_path = Path(save_path)
        target_dir = target_path.parent / target_path.stem if target_path.suffix else target_path

    if target_dir is not None:
        target_dir.mkdir(parents=True, exist_ok=True)

    G = nx.DiGraph(mask)
    saved_file_paths = []

    for agent_id in selected_agents:
        s = int(sd_mat[agent_id, 0])
        dest = int(sd_mat[agent_id, 1])

        start_time_val = float(start_times[agent_id]) if start_times is not None else 0.0
        speed_lim_val = speed_lim_mat[agent_id] if speed_lim_mat is not None else np.array([1.0, 10.0])
        process_t_val = processing_time[agent_id] if processing_time is not None else np.zeros(n_wp)

        ag = flpoAgent(
            n_wp=n_wp,
            sd=sd_mat[agent_id],
            sched=T_array[0, agent_id, :],
            start_time=start_time_val,
            speed=float(V_array[0, agent_id]),
            speedLim=speed_lim_val,
            process_T=process_t_val,
            INF=float(inf),
            offset_energy=bool(offset_energy),
            selfHop=bool(self_hop),
            net_mask=mask,
            stagewise_cost_coeffs=stagewise_cost_coeffs,
        )

        try:
            candidate_paths = list(itertools.islice(nx.shortest_simple_paths(G, source=s, target=dest), 50))
        except (nx.NetworkXNoPath, nx.NodeNotFound):
            candidate_paths = []

        opt_route = list(agent_routes[agent_id]) if agent_routes is not None and agent_id < len(agent_routes) else None

        paths = []
        if opt_route is not None and len(opt_route) > 1 and int(opt_route[0]) == s and int(opt_route[-1]) == dest:
            paths.append([int(x) for x in opt_route])

        for pth in candidate_paths:
            pth_int = [int(x) for x in pth]
            if pth_int not in paths and len(paths) < num_paths:
                paths.append(pth_int)

        if not paths:
            paths = [[s, dest]]

        def _compute_path_prob(path, Pb):
            K = len(Pb)
            prob = 1.0
            prob *= float(Pb[0][0, path[1]])
            for step in range(1, len(path) - 1):
                prob *= float(Pb[step][path[step], path[step + 1]])
            for step in range(len(path) - 1, K - 1):
                prob *= float(Pb[step][dest, dest])
            prob *= float(Pb[K - 1][dest, 0])
            return prob

        probs_mat = np.zeros((n_beta, len(paths)))
        for b_i, beta in enumerate(b_arr):
            sched = T_array[b_i, agent_id, :]
            speed = float(V_array[b_i, agent_id])
            Pb = ag.getPathAssociations_v1(sched, speed, dist_mat, beta)
            for p_i, path in enumerate(paths):
                probs_mat[b_i, p_i] = _compute_path_prob(path, Pb)

        fig, ax = plt.subplots(figsize=(10, 10))

        im = ax.imshow(probs_mat, cmap="Blues", aspect="auto", vmin=0.0, vmax=1.0, origin="lower")

        for r in range(n_beta):
            for c in range(len(paths)):
                val = probs_mat[r, c]
                text_color = "white" if val > 0.6 else "black"
                ax.text(c, r, f"{val:.2f}", ha="center", va="center", color=text_color, fontsize=18, fontweight="bold")

        ax.set_xticks(np.arange(len(paths)))
        ax.set_xticklabels([f"{i+1}" for i in range(len(paths))], fontsize=x_tick_size, fontweight="bold")
        ax.set_yticks(np.arange(n_beta))
        ax.set_yticklabels([rf"${b:.2g}$" for b in b_arr], fontsize=y_tick_size)
        ax.set_xlabel("Sampled Path ID", fontsize=label_size, fontweight="bold", labelpad=10)
        ax.set_ylabel(r"$\beta$", fontsize=label_size, fontweight="bold")
        ax.set_title(f"Agent {agent_id} (Start: {s} $\\to$ End: {dest})", fontsize=title_size, fontweight="bold", pad=12)

        legend_handles = [
            mpatches.Patch(color="none", label=f"Path {i+1}: " + " $\\to$ ".join(map(str, pth)))
            for i, pth in enumerate(paths)
        ]
        ax.legend(
            handles=legend_handles,
            loc="upper center",
            bbox_to_anchor=(0.5, -0.12),
            fontsize=legend_size,
            frameon=True,
            framealpha=0.9,
            title="Path Sequences",
            title_fontsize=legend_size + 2,
            alignment="left",
        )

        cbar = fig.colorbar(im, ax=ax, shrink=0.85, pad=0.03, aspect=20)
        cbar.set_label("Path Probability", fontsize=label_size, fontweight="bold")
        cbar.ax.tick_params(labelsize=y_tick_size)

        if target_dir is not None:
            agent_file_path = target_dir / f"agent_{agent_id}_path_probability_vs_beta.png"
            fig.savefig(agent_file_path, dpi=dpi, bbox_inches="tight")
            saved_file_paths.append(agent_file_path)

        if show_plot:
            plt.show()

        plt.close(fig)

    return saved_file_paths